core/blog/urls.py
from django.urls import path
from .views import BlogIndexView, RedticetViewTest, PostListView, PostDetailView, CreatePostView, UpdatePostView, PostDeleteView

app_name = 'blog'
urlpatterns  = [
    path('index', BlogIndexView.as_view(), name='index'),
    path('index-2/<int:pk>/', RedticetViewTest.as_view(), name='redirect_view'),
    path('posts/', PostListView.as_view(), name='posts_list'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', CreatePostView.as_view(), name='post_create'),
    path('posts/update/<int:pk>/', UpdatePostView.as_view(), name='update_view'),
    path('posts/delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    
    def __str__(self):
        return f"User:{self.email}"



class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    descriptiom = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"Profile For:{self.user.email}"

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# get user Model Form Project
User = get_user_model()

class Post(models.Model):
    '''
    This Class Can Defiend posts in blog app
    '''
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    content = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.BooleanField(default=False)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()


    def __str__(self):
        return self.title

    def get_absloute_url(self):
        return reverse('blog:post_detail', args=[self.id])


class Category(models.Model):
    name = models.CharField(max_length=110)
    

core/blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('author',)



# class PostCreateForm(forms.Form):
#     title = forms.CharField(max_length=110)
#     image = forms.ImageField()
#     content = forms.Textarea()
#     status = forms.BooleanField(widget=forms.CheckboxInput())

core/accounts/views.py
from django.shortcuts import render

# Create your views here.

core/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, RedirectView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import PostCreateForm

class BlogIndexView(TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'name': 'mohammad '
        }

        return context


class RedticetViewTest(RedirectView):
    pattern_name = 'blog:index'
    def get_redirect_url(self, *args ,**kwargs):
        article_id = kwargs['pk']
        post = get_object_or_404(Post, id=article_id)
        print(post)
        return super().get_redirect_url(*args,**kwargs)



class PostListView(ListView):

    queryset = Post.objects.all()
    paginate_by = 2
    allow_empty = False # if This Atter is False its mean Django Should Raise A 404 Error For User
    context_object_name = 'posts'
    template_name = 'blog/posts_list.html'


class PostDetailView(DetailView):
    template_name = 'blog/post_detail.html'
    model = Post
    context_object_name = 'post'



class CreatePostView(PermissionRequiredMixin,LoginRequiredMixin, CreateView):
    permission_required = 'blog.add_post'
    template_name = 'blog/post_create.html'
    success_url = '/blog/posts/'
    form_class = PostCreateForm


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class UpdatePostView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_create.html'
    success_url = '/blog/posts/'
    form_class = PostCreateForm


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/blog/posts/'
    template_name_suffix = '_delete'

core/blog/templates/blog/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Submit
        </button>
    </form>
</body>
</html>

core/blog/templates/blog/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Are You Sure Delte This Post? {{ object }}
        <button type="submit">
            Delete
        </button>
    </form>
</body>
</html>

core/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Detail For {{ post.title }}</title>
</head>
<body>
    <h1>
        Title : {{ post.title }}
        Author : {{ post.author }}
    </h1>
    <img src="{{ post.image.url }}" alt="">
   <p>

    {{ post.content }}
    <hr>
    <p>Publish Date:{{ post.published_date }}</p>
   </p>
</body>
</html>

core/blog/templates/blog/posts_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        Last posts
    </h1>
    {% for post in posts %}
    <div>
        <a href="{{ post.get_absloute_url }}"><h2>Title:{{ post.title }}</h2></a>
        <a href="{% url 'blog:update_view' post.id %}">
            <h5>Update</h5>
            
        </a>
        <a href="{% url 'blog:post_delete' post.id %}">
            <h6>Delete</h6>
        </a>
        <p>
            {{ post.content|safe }}
        </p>
    </div>
    
    {% endfor %}
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% for page in page_obj.paginator.page_range  %}
            <a href="?page={{ page }}">{{ page }}</a>
            {% endfor %}
        </span>
    </div>
    {% endif %}
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
</html>